name: Build wheels

on:
  release:
    types: [published]

  # Enable manual run
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # Used to host cibuildwheel
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.2.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp27-* cp35-* pp* *-musllinux_*"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          name: bdist_files

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Build sdist (pep517)
        run: |
          python -m pip install pep517
          python -m pep517.build -s .
      - name: Upload sdist
        uses: actions/upload-artifact@v2
        with:
          name: sdist_files
          path: dist/*.tar.gz
          
  publish_wheels:
    name: Publish wheels on pypi
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
      
      - name: install requirements
        run: pip install twine==3.4.2

      - uses: actions/download-artifact@v2
        with:
          name: bdist_files
          path: dist

      - uses: actions/download-artifact@v2
        with:
          name: sdist_files
          path: dist
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.1
        with:
          workload_identity_provider: "projects/137670451433/locations/global/workloadIdentityPools/python-ar-pool-1hyp/providers/python-gh-provider"
          service_account: "ki-pypi@ki-artifact-registries-cf08.iam.gserviceaccount.com"

      - name: check
        run: twine check dist/*
        
      - name: upload
        run: twine upload dist/*
        env:
          TWINE_REPOSITORY_URL: https://europe-python.pkg.dev/ki-artifact-registries-cf08/ki-pypi/
          TWINE_USERNAME: oauth2accesstoken
          TWINE_PASSWORD: $(gcloud auth print-access-token)
